### ISSUE TITLE
Allow Ruuter to make requests to other localhost services binded with ports

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Maintenance#6]
AS A Developer
I WANT TO make requests via Ruuter to different localhost services running on different ports
SO THAT I could use my usual development environment

### Acceptance Criteria

- [ ] Make sure to have http://localhost:<port-nr> as a running (not Ruuter) service
- [ ] Create a simple Ruuter DSL to make a GET request to http://localhost:<port>
- [ ] Use this Ruuter DSL service via browser
- [ ] Response of http://localhost:<port> is provided by Ruuter

**Comment by turnerrainer** [comment]
#### Step 1 - update Ruuter's `docker-compose.yml`

Add `extra_hosts` under `services.ruuter`

`docker-compose.yml` should look like this:

```yaml
version: '3.9'
services:
  ruuter:
    container_name: ruuter
    build:
      context: .
    volumes:
      - ./DSL:/DSL
    ports:
      - 8080:8080
    networks:
      - ruuter
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ruuter:
    driver: bridge
```

#### Step 2 - change localhost URL's in Ruuter DSLs

When using `localhost:<port>` URLs in Ruuter DSLs to use other than Ruuter itself, replace `http://localhost:<port>` with `http://host.docker.internal:<port>`

A working example `/DSL/GET/mocks/localhost.yml` looks like

```yaml
step_1:
  call: http.get
  args:
    url: http://host.docker.internal:8085
  result: nginx

step_2:
  return: ${nginx.response}
```
